name: pytorchbook
channels:
  - pytorch
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.11.5=py37he75722e_1
  - chardet=3.0.4=py37_1
  - conda=4.6.12=py37_1
  - conda-env=2.6.0=1
  - cryptography=2.4.2=py37h1ba5d50_0
  - freetype=2.9.1=h8a8886c_1
  - idna=2.8=py37_0
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py37h6bb024c_1
  - numpy=1.16.2=py37h7e9f1db_0
  - numpy-base=1.16.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h7b6447c_1
  - pillow=5.4.1=py37h34e0f95_0
  - pip=18.1=py37_0
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pyopenssl=18.0.0=py37_0
  - pysocks=1.6.8=py37_0
  - python=3.7.1=h0371630_7
  - pytorch-cpu=1.0.1=py3.7_cpu_2
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - setuptools=40.6.3=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision-cpu=0.2.2=py_3
  - urllib3=1.24.1=py37_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.0
    - astor==0.7.1
    - bcrypt==3.1.6
    - entrypoints==0.3
    - flake8==3.7.7
    - gast==0.2.2
    - grpcio==1.19.0
    - h5py==2.9.0
    - hiredis==1.0.0
    - jeepney==0.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.0.1
    - mccabe==0.6.1
    - mock==2.0.0
    - mypy==0.670
    - mypy-extensions==0.4.1
    - pbr==5.1.3
    - pipenv==2018.11.26
    - protobuf==3.7.0
    - psutil==5.6.1
    - pyasn1==0.4.5
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pynacl==1.3.0
    - redis==3.2.1
    - redisai==0.1.0
    - secretstorage==3.1.1
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - tqdm==4.31.1
    - typed-ast==1.3.1
    - virtualenv==16.4.3
    - virtualenv-clone==0.5.1
    - werkzeug==0.14.1

